- name: Ensure UFW package is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Set default incoming policy to deny
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set default outgoing policy to allow
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Allow SSH port through UFW
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Rate limit SSH port through UFW
  community.general.ufw:
    rule: limit
    port: "{{ ssh_port }}"
    proto: tcp

- name: Allow HTTP through UFW
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow HTTPS through UFW
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: Allow configured NodePort TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ nodeport_tcp_allow }}"

- name: Allow configured NodePort UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop: "{{ nodeport_udp_allow }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled
